name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest requests python-dotenv httpx ruff black

      - name: Ruff (lint, no autofix)
        run: |
          ruff check . --format=github --exit-non-zero-on-fix --no-fix

      - name: Black (format check)
        run: |
          black --check .

      - name: Pytest
        env:
          SIGNING_SECRET: dev-secret
        run: |
          python -m pytest -q
